server {
  listen 8080;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass https://tramites-backend-170902952348.us-east1.run.app/api/;
    proxy_set_header Host tramites-backend-170902952348.us-east1.run.app;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_ssl_server_name on;
  }

  location /ws {
    proxy_pass https://tramites-backend-170902952348.us-east1.run.app/ws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host tramites-backend-170902952348.us-east1.run.app;
    proxy_ssl_server_name on;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
